import models.user.Profile;
import models.restaurant.Dish;
 
dialect "mvel"

/*RULES FOR 7ο βήμα υπολογισμού (εννοιολογικός) */

/*
 * This set of rules sets dish priorities due to HYPERURICEMIA 
 */

rule "Excludes for users with HYPERURICEMIA"
    when
        $u : Profile(hasHyperuricemia == true)    
        $dish : Dish()
   		eval($dish.getListOfIngredientConditionsArrayStr() contains "4")  
    then
    	$dish.exclude = true;
        System.out.println("Rule (excludes for users with HYPERURICEMIA): " + $dish.exclude);    
end


