import models.user.Profile;
import models.restaurant.Dish;
 
dialect "mvel"
 
/*RULES FOR 7ο βήμα υπολογισμού (εννοιολογικός) */

/*
 * This set of rules sets dish priorities due to CELIAC Disease 
 */



rule "Excludes for users with CELIAC Disease"
    when
       $u : Profile(hasCeliac == true)    
        $dish : Dish()
   		eval($dish.getListOfIngredientConditionsArrayStr() contains "3")  
    then
    	$dish.exclude = true;
        System.out.println("Rule (excludes for users with CELIAC Disease): " + $dish.exclude);    
end

