import models.user.Profile;
import models.restaurant.Dish;
 
dialect "mvel"
 
/*RULES FOR 8ο βήμα υπολογισμού (εννοιολογικός) */

/*
 * This set of rules Includes/ Excludes dishes based on preferences for eggs  
 */

rule "Includes dishes based on preferences for eggs"
    when $u : Profile(wantEggs==2)
    	$dish : Dish()
   		eval($dish.getListOfIngredientCategoriesArrayStr() contains "1")
    then
    	$dish.priority = 2;
        System.out.println("Rule (user LIKES eggs): " + $dish.priority);    
end

rule "Excludes dishes based on preferences for eggs"
    when $u : Profile(wantEggs==1)
     $dish : Dish()
   		eval($dish.getListOfIngredientCategoriesArrayStr() contains "1") 
    then
    	$dish.exclude = true;
        System.out.println("Rule (user DOES NOT LIKE eggs): " + $dish.exclude);    
end


