import models.user.Profile;
import models.restaurant.Dish;
 
dialect "mvel"
 
/*RULES FOR 8ο βήμα υπολογισμού (εννοιολογικός) */

/*
 * This set of rules Includes/ Excludes dishes based on preferences for seeds  
 */


rule "Includes dishes based on preferences for seeds"
    when $u : Profile(wantSeeds==2)
	    $dish : Dish()
   		eval($dish.getListOfIngredientCategoriesArrayStr() contains "13")
    then
    	$dish.priority = 2;
        $dish.seedsPriority = 1;
        System.out.println("Rule (user LIKES seeds): " + $dish.priority);    
end

rule "Excludes dishes based on preferences for seeds"
    when $u : Profile(wantSeeds==1)
     	$dish : Dish()
   		eval($dish.getListOfIngredientCategoriesArrayStr() contains "13")
    then
    	$dish.exclude = true;
        System.out.println("Rule (user DOES NOT LIKE seeds): " + $dish.exclude);    
end
