import models.user.Profile;
import models.restaurant.Dish;
 
dialect "mvel"
 
/*RULES FOR 8ο βήμα υπολογισμού (εννοιολογικός) */

/*
 * This set of rules Includes/ Excludes dishes based on preferences for sogia  
 */


rule "Includes dishes based on preferences for shells"
    when $u : Profile(wantShells==2)
    	$dish : Dish()
   		eval($dish.getListOfIngredientCategoriesArrayStr() contains "7")
    then
    	$dish.priority = 2;
        $dish.shellsPriority = 1;        
        System.out.println("Rule (user LIKES shells): " + $dish.priority);    
end

rule "Excludes dishes based on preferences for shells"
    when $u : Profile(wantShells==1)
     	$dish : Dish()
   		eval($dish.getListOfIngredientCategoriesArrayStr() contains "7") 
    then
    	$dish.exclude = true;
        System.out.println("Rule (user DOES NOT LIKE shells): " + $dish.exclude);    
end


