import models.user.Profile;
import models.restaurant.Dish;
 
dialect "mvel"
 
/*RULES FOR 8ο βήμα υπολογισμού (εννοιολογικός) */

/*
 * This set of rules Includes/ Excludes dishes based on preferences for feta  
 */

rule "Includes dishes based on preferences for feta"
    when $u : Profile(wantFeta==2)
    	$dish : Dish()
   		eval($dish.getListOfIngredientCategoriesArrayStr() contains "5")
    then
    	$dish.priority = 2;
        System.out.println("Rule (user LIKES feta): " + $dish.priority);    
end

rule "Excludes dishes based on preferences for feta"
    when $u : Profile(wantFeta==1)
     	$dish : Dish()
   		eval($dish.getListOfIngredientCategoriesArrayStr() contains "5") 
    then
    	$dish.exclude = true;
        System.out.println("Rule (user DOES NOT LIKE feta): " + $dish.exclude);    
end


