import models.user.Profile;
import models.restaurant.Dish;
 
dialect "mvel"
 
/*RULES FOR 8ο βήμα υπολογισμού (εννοιολογικός) */

/*
 * This set of rules Includes/ Excludes dishes based on preferences for milk  
 */

rule "Includes dishes based on preferences for milk"
    when $u : Profile(wantMilk==2)
	    $dish : Dish()
   		eval($dish.getListOfIngredientCategoriesArrayStr() contains "3")
    then
    	$dish.priority = 2;
        System.out.println("Rule (user LIKES milk): " + $dish.priority);    
end

rule "Excludes dishes based on preferences for lamp"
    when $u : Profile(wantMilk==1)
	    $dish : Dish()
   		eval($dish.getListOfIngredientCategoriesArrayStr() contains "3")
    then
    	$dish.exclude = true;
        System.out.println("Rule (user DOES NOT LIKE milk): " + $dish.exclude);    
end


