import models.user.Profile;
import models.restaurant.Dish;
 
dialect "mvel"
 
/*RULES FOR 8ο βήμα υπολογισμού (εννοιολογικός) */

/*
 * This set of rules Includes/ Excludes dishes based on preferences for kaseri  
 */

rule "Includes dishes based on preferences for kaseri"
    when $u : Profile(wantKaseri==2)
	    $dish : Dish()
   		eval($dish.getListOfIngredientCategoriesArrayStr() contains "4")
    then
    	$dish.priority = 2;
        System.out.println("Rule (user LIKES kaseri): " + $dish.priority);    
end

rule "Excludes dishes based on preferences for kaseri"
    when $u : Profile(wantKaseri==1)
	    $dish : Dish()
   		eval($dish.getListOfIngredientCategoriesArrayStr() contains "4")  
    then
    	$dish.exclude = true;
        System.out.println("Rule (user DOES NOT LIKE kaseri): " + $dish.exclude);    
end


