import models.user.Profile;
import models.restaurant.Dish;
 
dialect "mvel"
 
/*RULES FOR 8ο βήμα υπολογισμού (εννοιολογικός) */

/*
 * This set of rules Includes/ Excludes dishes based on preferences for sogia  
 */


rule "Includes dishes based on preferences for veal"
    when $u : Profile(wantVeal==2)
   	 	$dish : Dish()
   		eval($dish.getListOfIngredientCategoriesArrayStr() contains "6")
    then
    	$dish.priority = 2;
      $dish.vealPriority = 1;
        System.out.println("Rule (user LIKES veal): " + $dish.priority);    
end

rule "Excludes dishes based on preferences for eggs"
    when $u : Profile(wantVeal==1)
     	$dish : Dish()
   		eval($dish.getListOfIngredientCategoriesArrayStr() contains "6")
    then
    	$dish.exclude = true;
        System.out.println("Rule (user DOES NOT LIKE veal): " + $dish.exclude);    
end


