import models.user.Profile;
import models.restaurant.Dish;
 
dialect "mvel"
 
/*RULES FOR 8ο βήμα υπολογισμού (εννοιολογικός) */

/*
 * This set of rules Includes/ Excludes dishes based on preferences for wheat  
 */


rule "Includes dishes based on preferences for wheat"
    when $u : Profile(wantWheat==2)
    	$dish : Dish()
   		eval($dish.getListOfIngredientCategoriesArrayStr() contains "10")
    then
    	$dish.priority = 2;
        System.out.println("Rule (user LIKES wheat): " + $dish.priority);    
end

rule "Excludes dishes based on preferences for wheat"
    when $u : Profile(wantWheat==1)
     	$dish : Dish()
   		eval($dish.getListOfIngredientCategoriesArrayStr() contains "10")  
    then
    	$dish.exclude = true;
        System.out.println("Rule (user DOES NOT LIKE wheat): " + $dish.exclude);    
end

