import models.user.Profile;
import models.restaurant.Dish;
 
dialect "mvel"
 
/*RULES FOR 8ο βήμα υπολογισμού (εννοιολογικός) */

/*
 * This set of rules Includes/ Excludes dishes based on preferences for lamp  
 */

rule "Includes dishes based on preferences for lamp"
    when $u : Profile(wantLamp==2)
	    $dish : Dish()
   		eval($dish.getListOfIngredientCategoriesArrayStr() contains "2")
    then
    	$dish.priority = 2;
        $dish.lampPriority = 1;        
        System.out.println("Rule (user LIKES lamp): " + $dish.priority);    
end

rule "Excludes dishes based on preferences for lamp"
    when $u : Profile(wantLamp==1)
	     $dish : Dish()
   		 eval($dish.getListOfIngredientCategoriesArrayStr() contains "2")
    then
    	$dish.exclude = true;
        System.out.println("Rule (user DOES NOT LIKE lamp): " + $dish.exclude);    
end


